export const AUTH_SIGN_IN_REQUEST = 'AUTH_SIGN_IN_REQUEST';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILURE = 'AUTH_SIGN_IN_FAILURE';

export const AUTH_SIGN_OUT_REQUEST = 'AUTH_SIGN_OUT_REQUEST';
export const AUTH_SIGN_OUT_SUCCESS = 'AUTH_SIGN_OUT_SUCCESS';
export const AUTH_SIGN_OUT_FAILURE = 'AUTH_SIGN_OUT_FAILURE';

export const AUTH_SET_USER = 'AUTH_SET_USER';

export const CATEGORIES_GET_REQUEST = 'CATEGORIES_GET_REQUEST';
export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCESS';
export const CATEGORIES_GET_FAILURE = 'CATEGORIES_GET_FAILURE';

export const VERSES_CREATE_REQUEST = 'VERSES_CREATE_REQUEST';
export const VERSES_CREATE_SUCCESS = 'VERSES_CREATE_SUCCESS';
export const VERSES_CREATE_FAILURE = 'VERSES_CREATE_FAILURE';

export const GLOBAL_TOGGLE_LOADING = 'GLOBAL_TOGGLE_LOADING';