export const AUTH_SIGN_IN_REQUEST = 'AUTH_SIGN_IN_REQUEST';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILURE = 'AUTH_SIGN_IN_FAILURE';

export const AUTH_SIGN_OUT_REQUEST = 'AUTH_SIGN_OUT_REQUEST';
export const AUTH_SIGN_OUT_SUCCESS = 'AUTH_SIGN_OUT_SUCCESS';
export const AUTH_SIGN_OUT_FAILURE = 'AUTH_SIGN_OUT_FAILURE';

export const AUTH_SET_USER = 'AUTH_SET_USER';

export const CATEGORIES_GET_REQUEST = 'CATEGORIES_GET_REQUEST';
export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCESS';
export const CATEGORIES_GET_FAILURE = 'CATEGORIES_GET_FAILURE';

export const CATEGORIES_DELETE_REQUEST = 'CATEGORIES_DELETE_REQUEST';
export const CATEGORIES_DELETE_SUCCESS = 'CATEGORIES_DELETE_SUCCESS';
export const CATEGORIES_DELETE_FAILURE = 'CATEGORIES_DELETE_FAILURE';

export const CATEGORIES_CREATE_REQUEST = 'CATEGORIES_CREATE_REQUEST';
export const CATEGORIES_CREATE_SUCCESS = 'CATEGORIES_CREATE_SUCCESS';
export const CATEGORIES_CREATE_FAILURE = 'CATEGORIES_CREATE_FAILURE';

export const VERSES_CREATE_REQUEST = 'VERSES_CREATE_REQUEST';
export const VERSES_CREATE_SUCCESS = 'VERSES_CREATE_SUCCESS';
export const VERSES_CREATE_FAILURE = 'VERSES_CREATE_FAILURE';

export const VERSES_UPDATE_REQUEST = 'VERSES_UPDATE_REQUEST';
export const VERSES_UPDATE_SUCCESS = 'VERSES_UPDATE_SUCCESS';
export const VERSES_UPDATE_FAILURE = 'VERSES_UPDATE_FAILURE';

export const VERSES_GET_REQUEST = 'VERSES_GET_REQUEST';
export const VERSES_GET_SUCCESS = 'VERSES_GET_SUCCESS';
export const VERSES_GET_FAILURE = 'VERSES_GET_FAILURE';

export const VERSES_DELETE_REQUEST = 'VERSES_DELETE_REQUEST';
export const VERSES_DELETE_SUCCESS = 'VERSES_DELETE_SUCCESS';
export const VERSES_DELETE_FAILURE = 'VERSES_DELETE_FAILURE';

export const VERSES_FORM_SET_VALUES = 'VERSES_FORM_SET_VALUES';

export const GLOBAL_TOGGLE_LOADING = 'GLOBAL_TOGGLE_LOADING';
export const GLOBAL_TOGGLE_DIALOG = 'GLOBAL_TOGGLE_DIALOG';